### ISSUE TITLE
Missing install repertory

### ISSUE THREAD

**Issue by bjuditt** [CERT-BDF/Cortex#1]
### Request Type
Bug

### Work Environment
Binary

### Problem Description
Hello, when trying to test cortex via binaries with thehive, I noticed that there was no install directory in the following packages
thehive-cortex-latest.zip and cortex-latest.zip

Thanks

**Comment by nadouani** [comment]
Hello @bjuditt,
thanks for reporting this issue. 

Well, you can get these files from https://github.com/CERT-BDF/Cortex/tree/master/install and we will fix the binaries ASAP

Thanks

**Comment by To-om** [comment]
Packages have been uploaded with install files.
