### ISSUE TITLE
Documentation on 'How to create an analyzer'

### ISSUE THREAD

**Issue by Popsiclestick** [CERT-BDF/Cortex#10]
### Request Type
Documentation Request

### Problem Description
You have a link in your wiki - https://github.com/CERT-BDF/Cortex/wiki/How-to-create-an-analyzer
This currently doesn't go to anything, these instructions would be particularly useful to those who would like to start contributing analyzers to Cortex right now.

**Comment by saadkadhi** [comment]
@Popsiclestick You are correct. This link is a place holder. We are going to create and populate the page in the next few days. We realize this is very important for the community.

**Comment by nadouani** [comment]
The **How to create an analyzer** guide is ready: https://github.com/CERT-BDF/Cortex/wiki/How-to-create-an-analyzer
