### ISSUE TITLE
Add proxy authentication

### ISSUE THREAD

**Issue by 007m56** [CERT-BDF/Cortex#15]
The HTTP client of Play can use proxy settings of the JVM but can't handle authentication. Please add support for proxy authentication.

**Comment by nadouani** [comment]
Hi @007m56, Cortex (and Play) are not using any proxy. Are you talking about the proxy in from of Cortex (when called from TheHive for example) or the proxy used by analyzers to call external services?

**Comment by 007m56** [comment]
Hi, I've in mind the proxy used by analyzers to call external services, like virustotal an so on.

**Comment by nadouani** [comment]
OK this is in fact a feature that needs to be supported by the analyzers. We need to find a way to make this available on cortexutils library.
