### ISSUE TITLE
Cortex 1.1.0 doesnt work with theHive 2.11.0

### ISSUE THREAD

**Issue by ST2Labs** [CERT-BDF/Cortex#24]
### Request Type
Bug Maybe

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       |  Ubuntu 16.04
| Cortex version / git hash   | 1.1.0
| Package Type              | Binary & Deb
| Browser type & version    |  Firefox

### Problem Description
Yesterday i'm upgrading TheHive 2.10 - 2.11 all goes well | I have using "binary" deployment and all was ok.

Cortex engine is 1.0.1 and work with TheHive 2.11, I have my own analyzers, and work ok. But I tried to upgrade Cortex 1.0.1 to 1.1.0 Binary first and later, from deb package.

1) First| Problem, When I start Cortex doesnt show any analyzers , y check application.conf and all seems ok.

2) From package deb, the same problema, when I start Cortex-1.1.0 analyzers doesnt show, any analyzers. 

I back to cortex 1.0.1 and work well | Maybe some bugs? any new config files to be configured?

Thanks in advance, I want to "release" my analyzers soon with us support!

**Comment by jeromeleonard** [comment]
Hello ST2Labs, 

Thank you for your reporting. 
Did you update Cortex-analyzers as well ? we have added licenses and authors in each individual JSON configuration file that cortex is looking for to run each analyzer properly.

**Comment by ST2Labs** [comment]
Hi Jero,

 OK, I wil try and tell you.

Thanks !!

**Comment by ST2Labs** [comment]
Thanks !! Now Work properly!

 👍
