### ISSUE TITLE
jobstatus from jobs within cortex are not updated when status changes

### ISSUE THREAD

**Issue by crackytsi** [CERT-BDF/Cortex#31]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian 8
| Cortex version / git hash   |1.1.1-2
| Package Type              | Debian Package

### Problem Description
If you manually submit a Job in Cortex via webfrontend, the Job Status is not refreshed. So the new Status only appears if you reclick on the joblist.

By the way: At the very bottom of the page appears: VERSION: Snapshot
I would expect Version 1.1.1...

**Comment by nadouani** [comment]
I'm able to reproduce the `Version: SNAPSHOT` issue, but not the jobs list refresh.

@crackytsi How did you run the analyzer? From the analyzers list or from the nav bar button?

**Comment by crackytsi** [comment]
I did the run via Cortex User-Webinterface  (Click on "Analyzers", filter for Analyzer e.g. MISP, Click "Run" ...)
