### ISSUE TITLE
No module named cortexutils.analyzer in abusefinder.py

### ISSUE THREAD

**Issue by Ibrahimous** [CERT-BDF/Cortex#34]
# No module named cortexutils.analyzer in abusefinder.py

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS 7 (Kernel 3.10.0-514)
| Cortex version / git hash   | 1.1.1
| Package Type              | Binary

### Problem Description
Describe the problem/bug as clearly as possible.

### Steps to Reproduce
1. Open Cortex GUI
1. launch Abuse_Finder_1_0
1. Go to Job report

{
  "errorMessage": "Error: Invalid output\nTraceback (most recent call last):\n  File \"./abusefinder.py\", line 8, in <module>\n    from cortexutils.analyzer import Analyzer\nImportError: No module named cortexutils.analyzer\n",
  "success": false
}

### Possible Solutions

Change #!/usr/bin/env python to use the python version of the virtual environment we have to use with TheHive and Cortex

### Complementary information
![cortex_bug](https://user-images.githubusercontent.com/3440845/27046620-6dbb2b6e-4fa5-11e7-9799-f74aac334ab2.jpg)

**Comment by nadouani** [comment]
Hello @Ibrahimous 
it looks like you don't have `cortexutils`library installed.

Did you follow the analyzers install guide?
https://github.com/CERT-BDF/CortexDocs/blob/master/installation/analyzers.md

Please install all the requirements and then reopen the issue if things are still broken.

Thanks

**Comment by Ibrahimous** [comment]
Bonjour @nadouani, 

Dans le contexte d'une installation déconnectée d'Internet, nous avons installé cortexutils en téléchargeant le module à la main, puis en faisant sudo pip install nom_du_module_téléchargé.
Le problème ici c’est qu'on a dû l’installer avec sudo, alors que quand on lance le script abuse_finder.py depuis la GUI, il lance le script avec l’utilisateur thehive.

L’utilisateur thehive ne trouve pas le module cortexutils du coup.

![cortexutils](https://user-images.githubusercontent.com/3440845/27073468-37cc0cd8-5024-11e7-8f26-b768a72d6b40.png)
![cortex_permission_denied](https://user-images.githubusercontent.com/3440845/27073467-37c1de2a-5024-11e7-82f0-f010e26834b1.png)

Merci par avance,

Clt

**Comment by nadouani** [comment]
pip modules should be installed using sudo, so this is not the problem.

Can you check the importing `cortexutils` works correctly? just open a python prompt and try importing cortexutils

<img width="654" alt="screen shot 2017-06-13 at 10 47 52" src="https://user-images.githubusercontent.com/21827/27073911-c9c6daa4-5025-11e7-973e-1dd96e2268c0.png">

**Comment by Ibrahimous** [comment]
![python_cortex_bis jpg](https://user-images.githubusercontent.com/3440845/27076010-3d10d46e-502c-11e7-82d7-c3285eb73c58.png)
![python_cortex](https://user-images.githubusercontent.com/3440845/27076009-3d10b9b6-502c-11e7-87f3-1ae08e73a39b.jpg)

**Comment by nadouani** [comment]
I've no idea how is this possible. I've just installed a fresh ubuntu VM and tested that, and works normally. Don't know what is happening with your pip installation

**Comment by nadouani** [comment]
@Ibrahimous did you solve the issue?

**Comment by Ibrahimous** [comment]
@nadouani nope, but it's probably linked to the way pip or python have been installed, not to Cortex

**Comment by nadouani** [comment]
It's for sure not a cortexutils issue, since I've tried starting from a fresh ubuntu VM, installer Python, Pip and the cortexutils and it worked fine. And AFAIK, this issue has never been raised by other users of Cortex. 

Is there any chance you can reinstall Python+PIP?

**Comment by Ibrahimous** [comment]
Yes, we'll try :)
Thx for your help !

**Comment by shubhamblackstratus** [comment]
Invalid output
Traceback (most recent call last):
  File "TorProject/tor_project_analyzer.py", line 2, in <module>
    from cortexutils.analyzer import Analyzer
ImportError: No module named 'cortexutils'

-------

Also find the 
![cortexutils](https://user-images.githubusercontent.com/25363342/44081817-4ab0d604-9fcd-11e8-9d87-2a3de539b467.jpg)
snap.

**Comment by mathgirl26** [comment]
Hi,

I have the same issue with RecordedFuture analyzer:
"errorMessage": "Invalid output\nTraceback (most recent call last):\n  
  File \"RecordedFuture/recordedfuture.py\", line 4, in <module>\n    
  from cortexutils.analyzer import Analyzer\nModuleNotFoundError: No module named 'cortexutils'\n",

I think the problem is "#!/usr/bin/env python3".
<img width="222" alt="issue-cortex" src="https://user-images.githubusercontent.com/25195782/58008985-c4da7600-7aed-11e9-8d7f-ad8519e5cb82.PNG">

As you can see in this picture, cortexutils is found in the file "/usr/lib/**python2.7**/site-packages/cortexutils/__init__.py"

It sould be also find in pyhton3x. So do you know how to solve that?

Thank you in advance for your help.

**Comment by nadouani** [comment]
Hello @mathgirl26 most of the analyzer use Python 3, some of them are still using Python2 (because if unavailable dependencies compatible with Python3).

You need to have `cortexutils` installed for both Python2 and Python3

Thanks
