### ISSUE TITLE
Cortex behind proxy

### ISSUE THREAD

**Issue by tatdatpham** [CERT-BDF/Cortex#40]
Feature Request

### Work Environment

OS version (server)  :  Centos 7

### Problem Description
My server is not public. It is interal network and using proxy server. How to config cortex job analyzer run behind proxy?

Exxample : Run Job OTXquery -> Connection syn_sent (because i'm ussing proxy). -> return error

**Comment by nadouani** [comment]
Hello,

You want to make your analyzers communicate to external services through a Proxy?

Take a look to https://github.com/CERT-BDF/CortexDocs/blob/master/installation/analyzers.md#configuration

**Comment by nadouani** [comment]
Please for more questions, let's talk at https://gitter.im/TheHive-Project/TheHive. Feel free to join the channel.

Thanks.
