### ISSUE TITLE
"TLP is higher than allowed" message with different analyzers

### ISSUE THREAD

**Issue by infsy** [CERT-BDF/Cortex#41]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | Windows 7
| Cortex version / git hash   | 1.1.3-1
| Package Type              | Binary (.deb)
| Browser type & version    | Opera 46.0

### Problem Description
I just finished to install TheHive-Cortex bundle on my server. I installed the analyzers too, regarding the official documentation. 
For some analyzers, it works well ! But for a few one, i've got the message "TLP is higher than allowed" coming from analyzer python file. I don't know why. 

For example, i've got this message when i use on a file (observable) the analyzer Vmray, or on a URL the analyzer WOT_Lookup.

I didn't find any information on this message, sorry if it's obvious...

### Steps to Reproduce
1. Install The Hive
2. Install Cortex
3. Install Analyzers
4. Test analyzers

### Complementary information

![bugcortex1](https://user-images.githubusercontent.com/1073400/30343108-3570db24-97ca-11e7-9e2b-1b580c388bec.png)

**Comment by saadkadhi** [comment]
@infsy The TLP of the observable you are submitting for analysis is higher than allowed to protect your OPSEC. For ex. if your URL is TLP:RED it should not be analyzed using an external service because you will be leaking it outside (which defeats the purpose of TLP:RED).

**Comment by infsy** [comment]
OMG, it's was definitively the dumbest question of the year... Sorry for that, i was to focusing on the installation details ! 
By the way, thank you for your job guys, these projects are amazing !

**Comment by saadkadhi** [comment]
Thank @infsy I'm gonna go ahead and close the issue.
