### ISSUE TITLE
Shodan Analyzer Fails - Module cortexutils Not Found

### ISSUE THREAD

**Issue by darksheer** [CERT-BDF/Cortex#55]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.0.4 LTS
| OS version (client)       | OS X
| Cortex version / git hash   | Latest
| Package Type              | Source
| Browser type & version    | Chrome (N/A)

### Problem Description
Enabling the Shodan analyzer fails with an error of:
```
Traceback (most recent call last):
  File "./shodan_analyzer.py", line 3, in <module>
    from cortexutils.analyzer import Analyzer
ImportError: No module named 'cortexutils'
```
To confirm it is installed:

```
root@ip-10-10-2-40:/opt/Cortex-Analyzers/analyzers/Shodan# pip search cortexutils
cortexutils (1.2.0)  - A Python library for including utility classes for Cortex analyzers
  INSTALLED: 1.2.0 (latest)
```

### Steps to Reproduce
1. Install Cortex
2. pip install requirements.txt (under Shodan Analyzer folder)
3. Execute the python script OR run the analyzer via WebUI

**Comment by darksheer** [comment]
Actually just caught that this module requires Python3, not Python2 like most of the modules.  Had to install pip3, then reinstall the requirements.txt

**Comment by darksheer** [comment]
Closing this for now, but there should probably be some thoughts on how to automate requirement installs for the analyzers.

**Comment by xme** [comment]
I've the same issue... Module installed for Python2 and Python3. Any idea?

**Comment by jeromeleonard** [comment]
@xme did you run `pip3 install cortexutils`  as a user or as root ? If install as user module may sit in the `homedir/.local` and not in the global installdir. In this case, uninstall the lib and reinstall it as root. Otherwise, maybe check permissions on `/usr/local/lib/python3.5/dist-packages/cortexutils` ; User `cortex` needs to have right to read and load the lib.

**Comment by xme** [comment]
As root because it's running in a docker. But I'll check this, could be the reason indeed!
